//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAPW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgramskoInzenjerstvoDBEntities : DbContext
    {
        public ProgramskoInzenjerstvoDBEntities()
            : base("name=ProgramskoInzenjerstvoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Djelovi> Djelovis { get; set; }
        public virtual DbSet<Kategorija> Kategorijas { get; set; }
        public virtual DbSet<Lokacija> Lokacijas { get; set; }
        public virtual DbSet<Lokacija_has_djelovi> Lokacija_has_djelovi { get; set; }
        public virtual DbSet<Model_vozila> Model_vozila { get; set; }
        public virtual DbSet<Narudzba> Narudzbas { get; set; }
        public virtual DbSet<Narudzba_has_Djelovi> Narudzba_has_Djelovi { get; set; }
        public virtual DbSet<Proizvodac> Proizvodacs { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Racun_Has_Djelovi> Racun_Has_Djelovi { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<Rezervacija_has_Djelovi> Rezervacija_has_Djelovi { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
        public virtual DbSet<Trgovina> Trgovinas { get; set; }
        public virtual DbSet<Zaposlenik> Zaposleniks { get; set; }
        public virtual DbSet<Zaposlenik_has_Tip> Zaposlenik_has_Tip { get; set; }
        public virtual DbSet<StanjeNaSkladistu> StanjeNaSkladistus { get; set; }
    }
}
