//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAPW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba_has_Djelovi
    {
        public int id_narudzbe { get; set; }
        public int id_djelovi { get; set; }
        public int kolicina { get; set; }
    
        public virtual Djelovi Djelovi { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
