//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAPW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzba()
        {
            this.Narudzba_has_Djelovi = new HashSet<Narudzba_has_Djelovi>();
        }
    
        public int id { get; set; }
        public System.DateTime datumKreiranja { get; set; }
        public Nullable<System.DateTime> datumPotvrde { get; set; }
        public string iznos { get; set; }
        public Nullable<int> kreirao { get; set; }
        public bool odobreno { get; set; }
        public Nullable<int> odobrio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba_has_Djelovi> Narudzba_has_Djelovi { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
        public virtual Zaposlenik Zaposlenik1 { get; set; }
    }
}
