//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAPW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.Racun_Has_Djelovi = new HashSet<Racun_Has_Djelovi>();
        }
    
        public int id { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<int> zaposlenik { get; set; }
        public string iznos { get; set; }
        public string Maloprodaja_veleprodaja { get; set; }
        public Nullable<int> trgovina { get; set; }
        public int lokacija { get; set; }
    
        public virtual Lokacija Lokacija1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun_Has_Djelovi> Racun_Has_Djelovi { get; set; }
        public virtual Trgovina Trgovina1 { get; set; }
        public virtual Zaposlenik Zaposlenik1 { get; set; }
    }
}
