//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAPW
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanjeNaSkladistu
    {
        public int id { get; set; }
        public string Dio { get; set; }
        public string kategorija { get; set; }
        public string Proizvođač { get; set; }
        public int kolicina { get; set; }
    }
}
